#!/bin/bash

# mute when clicked
if [[ "${BLOCK_BUTTON}" -eq 1 || "${BLOCK_BUTTON}" -eq 3 ]]; then
    amixer -D pulse set 'Master' 1+ toggle 1>/dev/null
fi

# get volume
statusLine=$(amixer get Master | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $4}' | tr -d '[]%')

if [[ "${status}" == "on" ]]; then
    if [ "$volume" -gt "60" ]; then
        icon="墳  "
    elif [ "$volume" -gt "35" ]; then
        icon="奔  "
    else
        icon="奄  "
    fi

    echo "${icon}${volume}%"
    echo "${icon}${volume}%"
    echo ""
else
    echo "婢  MUTE"
    echo "婢  MUTE"
    echo ""
fi
