#!/usr/bin/env sh

_launch() {
    # terminate already running bar instances
    killall -q polybar

    # wait until the processes have been shut down
    while pgrep -x polybar >/dev/null; do sleep 1; done

    # launch bar(s)
    polybar main -c $HOME/.config/bspwm/polybar/config.ini &

    [ "$1" = "--with-external" ] && \
        polybar external -c $HOME/.config/bspwm/polybar/config.ini &

    echo "Bar launched..."
}

while [ "$1" != "" ]; do
    case "$1" in
        --main)
            exit
            ;;

        --with-external)
            _launch $1
            exit
            ;;
                
        *)
            printf "Option '$1' is not available...\n"
            exit
            ;;
    esac
done
