syntax on
set mouse=a
set encoding=utf8
set clipboard=unnamedplus
set hidden
set number
set relativenumber
set backspace=2
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set laststatus=2

" netrw
let g:netrw_banner=0
let g:netrw_winsize=40
nnoremap <C-e> :Lexplore<CR>
