require("user.options")
require("user.plugins")
require("user.colorscheme")
require("user.mappings")
require("user.lsp")

require("user.alpha")
require("user.barbar")
require("user.gitsigns")
require("user.lualine")
require("user.nvim-tree")
require("user.telescope")
require("user.treesitter")
