#!/usr/bin/bash

INTERNAL="eDP1"
EXTERNAL_RIGHT="DP3"
EXTERNAL_LEFT="DP1"

if [[ $(xrandr -q | grep "^$EXTERNAL_RIGHT connected") ]];
then
    # monitor right
    xrandr \
        --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal \
        --output DP3 --primary --mode 1920x1080 --rate 60 --pos 1920x0 --rotate normal \
        --output DP1 --off \
        --output DP2 --off \
        --output HDMI-1 --off \
        --output HDMI-2 --off \
        --output HDMI-3 --off
elif [[ $(xrandr -q | grep "^$EXTERNAL_LEFT connected") ]];
then
    # monitor left
    xrandr \
        --output eDP1 --mode 1920x1080 --pos 320x1440 --rotate normal \
        --output DP1 --primary --mode 2560x1440 --pos 0x0 --rotate normal \
        --output DP2 --off \
        --output DP3 --off \
        --output HDMI-1 --off \
        --output HDMI-2 --off \
        --output HDMI-3 --off
else
    # only laptop
    xrandr \
        --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal \
        --output DP3 --off \
        --output DP1 --off \
        --output DP2 --off \
        --output HDMI-1 --off \
        --output HDMI-2 --off \
        --output HDMI-3 --off
fi
