#!/bin/bash

WMDIR="$HOME/.config/bspwm"

# startup
sxhkd -c $WMDIR/sxhkd/sxhkdrc &  # keychords
echo "Xft.dpi: 200" | xrdb &     # scaling for 4k monitor
picom &                          # compositor
nm-applet &                      # network-manager applet
dunst &                          # notification daemon
$HOME/.fehbg                     # set background with feh

# bspwm settings
bspc config border_width         5
bspc config window_gap           10
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color  "#4C566A"
bspc config focused_border_color "#0D73CC"

bspc rule -a zoom desktop="^9"
