#!/bin/bash

# bspwm directory
WM_DIR="$HOME/.config/bspwm"

# startup
sxhkd -c $WM_DIR/sxhkd/sxhkdrc &  # keychords
picom &                           # compositor
echo 'Xft.dpi: 200' | xrdb        # scaling for 4k monitor
nm-applet &                       # network-manager applet
$HOME/.fehbg                      # set background with feh


# bspwm settings
bspc config border_width         5
bspc config window_gap           10
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color  "#4c566a"
bspc config focused_border_color "#008080"

bspc rule -a zoom desktop='^7'
