#!/usr/bin/bash

INTERNAL="eDP-1"
EXTERNAL_RIGHT="DP-3"
EXTERNAL_LEFT="DP-1"

if [[ $(xrandr -q | grep "^$EXTERNAL_RIGHT connected") ]];
then
    # monitor right
    xrandr \
        --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal \
        --output DP-3 --primary --mode 1920x1080 --pos 1920x0 --rotate normal \
        --output DP-1 --off \
        --output DP-2 --off \
        --output HDMI-1 --off \
        --output HDMI-2 --off \
        --output HDMI-3 --off
elif [[ $(xrandr -q | grep "^$EXTERNAL_LEFT connected") ]];
then
    # monitor left
    xrandr \
        --output eDP-1 --mode 1920x1080 --pos 2560x0 --rotate normal \
        --output DP-1 --primary --mode 2560x1440 --pos 0x0 --rotate normal \
        --output DP-2 --off \
        --output DP-3 --off \
        --output HDMI-1 --off \
        --output HDMI-2 --off \
        --output HDMI-3 --off
else
    # only laptop
    xrandr \
        --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal \
        --output DP-3 --off \
        --output DP-1 --off \
        --output DP-2 --off \
        --output HDMI-1 --off \
        --output HDMI-2 --off \
        --output HDMI-3 --off
fi
