#!/bin/sh

chosen=$(printf "  Power Off\n  Reboot\n  Lock\n  Logout" | rofi -dmenu -i -p 'Run:' -l 4 -theme $HOME/.config/rofi/config.rasi)

case "$chosen" in
    "  Power Off")
        poweroff
        ;;

    "  Reboot")
        reboot
        ;;

    "  Lock")
        i3lock -c 1C1C1C
        ;;

    "  Logout")
        i3-msg exit
        ;;

    *)
        exit 1
        ;;
esac
