#!/bin/sh

chosen=$(printf "  Power Off\n  Reboot\n  Lock\n  Logout" | dmenu -i -l 5 -fn 'JetBrains Mono Nerd Font:pixelsize=14' -nb \#000000 -nf \#D4D4D4)

case "$chosen" in
    "  Power Off")
        poweroff
        ;;

    "  Reboot")
        reboot
        ;;

    "  Lock")
        i3lock -c 1C1C1C
        ;;

    "  Logout")
        i3-msg exit
        ;;

    *)
        exit 1
        ;;
esac
