#!/bin/sh

output="$HOME/Pictures/screenshots/%Y-%m-%d-%T-screenshot.png"
chosen=$(printf "Selection\nScreen" | dmenu -i -l 5 -fn 'JetBrains Mono Nerd Font:pixelsize=14' -nb \#000000 -nf \#D4D4D4)

case "$chosen" in
    "Selection")
        scrot "$output" --select --line mode=edge || exit
        ;;

    "Screen")
        scrot "$output" --focused --border || exit
        ;;

    *)
        exit
        ;;
esac

notify-send "Screenshot taken."
