#!/bin/sh

chosen=$(printf "  Power Off\n  Reboot\n  Lock\n  Logout" | rofi -dmenu -i -theme-str '@import "power.rasi"')

case "$chosen" in
	"  Power Off")
        poweroff
        ;;

	"  Reboot")
        reboot
        ;;

	"  Lock")
        i3lock -c 1C1C1C
        ;;

	"  Logout")
        bspc quit
        ;;
	
    *)
        exit 1
        ;;
esac
