#!/usr/bin/bash

MAIN="eDP-1"
EXTERNAL="DP-2"

if [[ $(xrandr -q | grep "$EXTERNAL connected") ]]; then
    xrandr \
        --output $MAIN --mode 3840x2160 --pos 3883x0 --rotate normal \
        --output $EXTERNAL --primary --mode 1920x1080 --pos 0x0 --rotate normal --scale 2x2
        
    bspc monitor $EXTERNAL -d '1' '2' '3' '4' '5' '6'
    bspc monitor $MAIN     -d '7'

    $HOME/.config/bspwm/polybar/launch-polybar &
else
    bspc monitor $MAIN -d '1' '2' '3' '4' '5' '6' '7'
fi
